---
title: "Erics Stuff"
author: "Eric Baxter"
date: "14/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
wine <- read.csv("data/processed/wine_quality.csv")
corr_df <- read.csv("data/processed/correlation.csv")
```


# Option 1: correlation matrix

```{r}
library(GGally)
ggpairs(wine, columns = 2: 5, ggplot2::aes(colour=Wine))
```

# Option 2

```{r}
library(ggcorrplot)
corr_red <- wine %>% filter(Wine == "red") %>% subset(select = -c(Wine, Quality.Factor)) %>% 
  cor()
corr_white <- wine %>% filter(Wine == "white") %>% subset(select = -c(Wine, Quality.Factor)) %>% cor()
```

```{r}
ggcorrplot(corr_red,
           hc.order = TRUE,
           type = "lower",
           outline.color = "white",
           color = c("darkred", "white", "darkred"))
ggcorrplot(corr_white,
           hc.order = TRUE,
           type = "upper",
           outline.color = "white",
           color = c("blue", "white", "blue"))
```

# Options list

```{r}
variables
```

```{r}
options <- list()
for (i in 1: length(variables)){
  options[i] <- list("label" = variables[i], "value" = variables[i])
}
```

```{r}
tree.variables <- colnames(wine)[2:6]
```

```{r}
wine[c("Wine", "Quality.Factor.Numeric", "Total.Sulfur.Dioxide..mg.dm.3.")]
```


```{r}
library(tree)
wine$Quality.Factor <- as.factor(wine$Quality.Factor)
wine$Wine <- as.factor(wine$Wine)
wine.tree.data <- cbind(wine[1:12], wine[14])
```
```{r}
wine.tree <- tree(Quality.Factor~ Wine + Alcohol....+ Chlorides..g.dm.3.,
                  data = wine.tree.data)

if(wine.tree$frame$splits[1] == ""){
  print("Insufficient predictive power from these variables to build tree")
} else {
  plot(wine.tree)
  text(wine.tree)
}
```


```{r}
plot(wine.tree); text(wine.tree)
```

```{r}
winetable <- wine[2:12]
winetable <- as.data.frame(summary(winetable))
# Remove empty first column
winetable <- winetable[c(2,3)]

winetable <- separate(winetable, Freq, into = c("Statistic", "Value"), sep = ":")

winetable <- spread(winetable, key = Statistic, value = Value)

names(winetable)[1] <- "Variables"
```

```{r}
write.csv(winetable, "summarystats.csv")
```


