---
title: "Rain_Plots"
author: "Rain Shen"
date: "3/15/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dash)
library(dashCoreComponents)
library(dashHtmlComponents)
library(dashBootstrapComponents)
library(ggplot2)
library(plotly)
```

```{r}
wine <- read.csv("C:/MDS/DATA551/WineVision-R-group8/data/processed/wine_quality.csv")
wine$id <- as.character(1:nrow(wine))
wine
```

```{r}
scatter <- ggplot(wine) + aes(x = Volatile.Acidity..g.dm.3., y = Fixed.Acidity..g.dm.3., color = Quality.Factor) + geom_point() + ggthemes::scale_color_tableau()
```

```{r}
ggplotly(scatter + aes(text=Quality.Factor), tooltip = 'Quality.Factor')
```
```{r}
msleep
```

```{r}
library(waffle)
wine_red <- wine %>% subset(Wine == "red")
wine_white <- wine %>% subset(Wine == "white")

table(wine_red$Quality.Factor)
table(wine_white$Quality.Factor)

red_counts <- c(`Above Average:`=217, `Average`=638, `Below Average`=744)
white_counts <- c(`Above Average:`=1060, `Average`=2195, `Below Average`=1640)

red <- waffle(red_counts/10, rows=5, size=0.6, 
              colors=c("#4E79A7", "#F28E2B", "#E15759"),
       title="Quality Factor Bifurcation",  
       xlab="1 square = 10 records")

white <- waffle(white_counts/30, rows=5, size=0.6,
                colors=c("#4E79A7", "#F28E2B", "#E15759"),
       title="Quality Factor Bifurcation",  
       xlab="1 square = 30 records")
white
```

```{r}
waffle.plot <- function(type) {
  if (type == "red") {
      return(red)
    } else {
      return(white)
    }
}
```

```{r}
waffle.plot("red")
```

```{r}
table(wine_red$Quality.Factor)/1599
table(wine_white$Quality.Factor)/4898

red_counts <- c(`Above Average:`=217, `Average`=638, `Below Average`=744)
white_counts <- c(`Above Average:`=1060, `Average`=2195, `Below Average`=1640)

red_prop <- c(`Above Average:`=217, `Average`=638, `Below Average`=744)
white_prop <- c(`Above Average:`=1060, `Average`=2195, `Below Average`=1640)
```

```{r}
b <- ggplot(wine, aes(x = Quality.Factor, fill=Quality.Factor)) +  
  geom_bar(aes(y = (..count..)/sum(..count..))) + ggthemes::scale_fill_tableau()
ggplotly(b, tooltip = 'y')
```

```{r}
wine$Quality.Factor <- as.factor(wine$Quality.Factor)
bp<- ggplot(wine, aes(x='', fill=Quality.Factor)) + geom_bar(position = "fill")+ ggthemes::scale_fill_tableau()
ggplotly(bp, tooltip = 'y')
```

```{r}
library(glmnet)
library(tidyverse)
grid = 10^seq(10,-2, length =100)

red <- wine %>% subset(Wine == "red")
white <- wine %>% subset(Wine == "white")
x <- as.matrix(white[,2:12])

wlas <- cv.glmnet(x, white$Quality, alpha = 1, nfolds=5)
plot(wlas)
```
```{r}
x2 <- as.matrix(red[,2:12])
rlas <- cv.glmnet(x2, red$Quality, alpha = 1, nfolds=5)
plot(rlas)
```
```{r}
wlas.mod <- glmnet(x, white$Quality, alpha = 1, lambda = grid)
plot(wlas.mod)
```

```{r}
bestlam = wlas$lambda.min
# lasso.pred = predict(wlas.mod, s = bestlam, newx=x[test ,])
# mean(( lasso.pred -y.test)^2)

lasso.coef = predict(wlas, type = "coefficients", s = bestlam)
lasso.coef
lasso.coef[lasso.coef != 0]
```

```{r}
bestlam2 = rlas$lambda.min
# lasso.pred = predict(wlas.mod, s = bestlam, newx=x[test ,])
# mean(( lasso.pred -y.test)^2)

lasso.coef2 = predict(rlas, type = "coefficients", s = bestlam2)
lasso.coef2
lasso.coef2[lasso.coef2 != 0]
```

